ComPWA/policy

reqs/3.6/requirements.txt
reqs/3.7/requirements.txt
reqs/3.8/requirements.txt
reqs/3.9/requirements.txt
setup.cfg
src/repoma/pre_commit_hooks/check_dev_files/__init__.py
src/repoma/pre_commit_hooks/check_dev_files/editor_config_hook.py

Check whether [this pre-commit hook for EditorConfig](https://github.com/editorconfig-checker/editorconfig-checker.python) has been added if an `.editorconfig` file is present.

feat: enforce editor config hook

---

.pre-commit-hooks.yaml
codecov.yml
setup.cfg
src/repoma/pre_commit_hooks/pin_nb_requirements.py

Designed particularly for https://github.com/ComPWA/compwa-org/issues/10

feat: add hook to pin requirements per notebook

---

src/repoma/.github/workflows/requirements-pr.yml

ci: abort requirements workflow if PR from fork

---

src/repoma/.github/workflows/cd.yml
src/repoma/check_dev_files/__init__.py
src/repoma/check_dev_files/github_workflows.py

feat: update CD workflow and push to minor branch

---

src/repoma/.github/workflows/requirements-pr.yml
src/repoma/check_dev_files/update_pip_constraints.py

Closes #37 
This changes the dependencies in the `requirements-pr.yml` workflow from
[![image](https://user-images.githubusercontent.com/29308176/144409901-151dd46e-fd9e-4412-b59c-50075de30ab2.png)](https://github.com/ComPWA/qrules/actions/runs/1529934975)
to
[![image](https://user-images.githubusercontent.com/29308176/144409782-d50c1a57-544e-4cd8-9558-2ba35aa5aaf3.png)](https://github.com/ComPWA/ampform/actions/runs/1530230379)
This PR is tested in ComPWA/ampform#186

ci: check for depenency changes in separate job

---

src/compwa_policy/check_dev_files/__init__.py
src/compwa_policy/check_dev_files/jupyter.py

Closes #324
See also https://github.com/ComPWA/compwa.github.io/pull/287

DX: enforce Ruff in Jupyter Lab

---

src/compwa_policy/check_dev_files/ruff.py

Adds `display` to the [`[tool.ruff.lint.flake8-builtins]`](https://docs.astral.sh/ruff/settings/#lint_flake8-builtins_builtins-ignorelist) table if the repository contains notebooks.

ENH: add `display` as allowed function name

---

docs/conf.py
src/compwa_policy/check_dev_files/prettier.py
src/compwa_policy/utilities/__init__.py
src/compwa_policy/utilities/cfg.py
src/compwa_policy/utilities/vscode.py

This makes it easier to remove keys from a nested structure.

BREAK: merge `vscode.remove_setting()` into `remove_settings()`

---

.pre-commit-config.yaml
src/compwa_policy/.template/.cspell.json
src/compwa_policy/check_dev_files/precommit.py
src/compwa_policy/check_dev_files/toml.py
src/compwa_policy/set_nb_cells.py
src/compwa_policy/utilities/precommit/struct.py
src/compwa_policy/utilities/pyproject/_struct.py

See https://github.com/ComPWA/taplo-pre-commit/pull/25

ENH: rename mirrors-taplo repo to taplo-pre-commit

---

pyproject.toml
src/compwa_policy/check_dev_files/black.py
src/compwa_policy/check_dev_files/ruff.py

ENH: remove `target-version` from `black` and `ruff` config

---

src/compwa_policy/check_dev_files/nbstripout.py

FIX: do not duplicate `nbstripout` `--extra-keys`

---

.cspell.json
src/compwa_policy/.template/.cspell.json

Required for https://github.com/ComPWA/sphinx-api-relink/pull/25

ENH: ignore `rst.jinja` files with cSpell

---

.github/workflows/clean-caches.yml
.github/workflows/release-drafter.yml
.github/workflows/sync-labels.yml
src/compwa_policy/.github/workflows/cd.yml
src/compwa_policy/check_dev_files/readthedocs.py
tests/check_dev_files/readthedocs/extend/.readthedocs-good.yml
tests/check_dev_files/readthedocs/overwrite/.readthedocs-good.yml
tests/check_dev_files/readthedocs/test_readthedocs.py

See https://github.com/ComPWA/actions/issues/85

BEHAVIOR: switch to `ubuntu-24.04`

---

.pre-commit-config.yaml
src/compwa_policy/check_dev_files/pyright.py
tests/check_dev_files/pyright/.pre-commit-config-good.yaml

See https://github.com/ComPWA/pyright-pre-commit/pull/2

MAINT: update pyright pre-commit hook URL

---

environment.yml
pyproject.toml
src/compwa_policy/check_dev_files/__init__.py
src/compwa_policy/check_dev_files/github_workflows.py
tests/check_dev_files/readthedocs/extend/.readthedocs-good.yml
tests/check_dev_files/readthedocs/overwrite/.readthedocs-good.yml
tests/check_dev_files/readthedocs/test_readthedocs.py

See also https://github.com/ComPWA/actions/pull/87

BEHAVIOR: use Python 3.12 in developer environment

---

.github/workflows/sync-labels.yml
pyproject.toml
src/compwa_policy/check_dev_files/__init__.py
src/compwa_policy/check_dev_files/conda.py
src/compwa_policy/check_dev_files/cspell.py
src/compwa_policy/check_dev_files/dependabot.py
src/compwa_policy/check_dev_files/precommit.py
src/compwa_policy/check_dev_files/prettier.py
src/compwa_policy/check_dev_files/pytest.py
src/compwa_policy/check_dev_files/pyupgrade.py
src/compwa_policy/check_dev_files/ruff.py
src/compwa_policy/check_dev_files/update_pip_constraints.py
src/compwa_policy/colab_toc_visible.py
src/compwa_policy/fix_nbformat_version.py
src/compwa_policy/remove_empty_tags.py
src/compwa_policy/set_nb_cells.py
src/compwa_policy/utilities/cfg.py
src/compwa_policy/utilities/precommit/struct.py
src/compwa_policy/utilities/pyproject/__init__.py
src/compwa_policy/utilities/pyproject/_struct.py
src/compwa_policy/utilities/pyproject/getters.py
src/compwa_policy/utilities/pyproject/setters.py
src/compwa_policy/utilities/toml.py
src/compwa_policy/utilities/vscode.py
tests/check_dev_files/editorconfig/test_editorconfig.py
tests/check_dev_files/pyright/test_pyright.py
tests/check_dev_files/test_cspell.py
tests/check_dev_files/test_pixi.py
tests/utilities/precommit/test_class.py

- Closes https://github.com/ComPWA/policy/issues/395

MAINT: drop Python 3.7 & 3.8 support due to EOL

---

pyproject.toml
src/compwa_policy/check_dev_files/__init__.py
src/compwa_policy/check_dev_files/pixi.py
src/compwa_policy/check_dev_files/setuptools_scm.py

ENH: remove post-version from dynamic version

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/clean-caches.yml
.github/workflows/pr-linting.yml
src/compwa_policy/.github/workflows/cd.yml
src/compwa_policy/.github/workflows/ci.yml
src/compwa_policy/.github/workflows/requirements.yml
src/compwa_policy/check_dev_files/github_workflows.py

See https://github.com/ComPWA/actions/issues/95

ENH: switch to ComPWA/actions@v2

---

src/compwa_policy/check_dev_files/__init__.py
src/compwa_policy/check_dev_files/github_workflows.py
src/compwa_policy/check_dev_files/release_drafter.py

- ENH: remove release drafter if `--no-cd`

FEAT: add `--no-cd` flag

---

src/compwa_policy/check_dev_files/binder.py

ENH: check if `notebooks` and `jupyter` dependencies exist

---

src/compwa_policy/.github/workflows/lock.yml

Add `**/Manifest.toml` (Julia) and `pixi.lock` to the trigger files for the `lock.yml` workflow.

MAINT: extend update-lock trigger patterns

---

src/compwa_policy/check_dev_files/jupyter.py

FIX: install all Jupyter extensions in one go

---

src/compwa_policy/check_dev_files/tox.py

FIX: wrap Tix `base` in list

---

CONTRIBUTING.md
src/compwa_policy/.template/CONTRIBUTING.md.jinja

Fixes this problem:
https://github.com/ComPWA/tensorwaves/actions/runs/12674769579/job/35324230702?pr=538

FIX: update link to `uv.lock` file explanation

---

.github/workflows/ci.yml
.vscode/settings.json
codecov.yml
pyproject.toml
src/compwa_policy/check_dev_files/github_workflows.py

Closes https://github.com/ComPWA/policy/issues/464

FIX: set `CODECOV_TOKEN`

---

pyproject.toml

- See https://github.com/ComPWA/policy/issues/493

MAINT: remove `pygments` version constraint

---

pyproject.toml
src/compwa_policy/utilities/pyproject/__init__.py
src/compwa_policy/utilities/pyproject/getters.py

BEHAVIOR: add Python 3.14 to allowed classifiers
