ComPWA/policy

src/repoma/pre_commit_hooks/check_dev_files/__init__.py, src/repoma/pre_commit_hooks/check_dev_files/editor_config_hook.py
Two fixes:
- The `check-dev-files` hook failed, because it did not take file names as argument.
- Its check on the pre-commit hook for Editor Config (see #7) was faulty
=> fix: make check-dev-files suitable for pre-commit

src/repoma/pre_commit_hooks/check_dev_files/cspell_config.py
The `check-dev-files` now checks whether the contents of entries in a `.cspell.json` config file are sorted.
=> feat: sort content in entries of cspell config

.pre-commit-config.yaml, setup.cfg, src/repoma/.cspell.json, src/repoma/pre_commit_hooks/check_dev_files/__init__.py, src/repoma/pre_commit_hooks/check_dev_files/cspell_config.py
Check whether the `.cspell.json` config contains all expected entries as defined in the [`src/repoma/.cspell.json`](https://github.com/ComPWA/repo-maintenance/blob/8bc89fb568385cead1367b8679c5c977576c68dc/src/repoma/.cspell.json) file.
=> feat: check missing entries cspell config

src/repoma/pre_commit_hooks/check_dev_files/__init__.py
Can be done with the `--alow-labels` argument in the `.pre-commit-config.yaml` file:
```yaml
- repo: https://github.com/ComPWA/repo-maintenance
rev: 0.0.6
hooks:
- id: check-dev-files
args:
- --allow-labels
```
=> feat: allow turning off label.toml check

src/repoma/pre_commit_hooks/check_dev_files/__init__.py, src/repoma/pre_commit_hooks/check_dev_files/update_requirements_workflows.py, src/repoma/workflows/requirements-cron.yml, src/repoma/workflows/requirements-pr.yml
Simplified upgrade workflows with the following two custom, composite GitHub Actions:
- https://github.com/ComPWA/update-pip-constraints
- https://github.com/ComPWA/update-pre-commit
The `pin_requirements.py` script is also removed from the `.constraints` folder.
=> feat: use new GitHub Actions in upgrade jobs

src/repoma/fix_first_nbcell.py, src/repoma/format_setup_cfg.py
Required for #43.
Other interface changes to the `fix-first-nbcell` hook:
- `--replace` argument has been removed. Whether to replace or insert is detected from the cell type.
- `--colab` argument has been renamed to `--add-install-cell`
- Added comma-separated `--extras-require` argument to specify more [optional dependencies](https://compwa-org.readthedocs.io/develop.html#optional-dependencies)
- Added comma-separated argument `--additional-packages` to install additional packages through `pip`
Tested on:
- https://github.com/ComPWA/qrules/pull/136
- https://github.com/ComPWA/ampform/pull/204
- https://github.com/ComPWA/tensorwaves/pull/400
=> feat: split and simplify notebook install cells

.pre-commit-config.yaml, src/repoma/check_dev_files/black.py, src/repoma/check_dev_files/editor_config.py, src/repoma/check_dev_files/flake8.py, src/repoma/check_dev_files/github_workflows.py, src/repoma/utilities/precommit.py, tests/check_dev_files/test_black.py, tests/utilities/test_cfg.py
Black made it's first non-beta release: [v22.1.0](https://github.com/psf/black/releases/tag/22.1.0). Repo-maintenance will:
- enforce [`preview = true`](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style) instead of experimental string processing
- enforce this first release on `nbqa-black`
=> feat: upgrade to non-beta black release

.pre-commit-config.yaml, pyproject.toml, src/repoma/fix_first_nbcell.py
The `fix-first-nbcell` hook now adds an [`autolink-concat`](https://sphinx-codeautolink.readthedocs.io/en/latest/reference.html#directive-autolink-concat) directive to each notebook. This behaviour can be deactivated globally with:
```yaml
- repo: https://github.com/ComPWA/repo-maintenance
rev: ...
hooks:
- id: fix-first-nbcell
args:
- --no-autolink-concat
```
or per notebook by writing the following comment in any markdown cell:
```markdown
```
=> feat: insert autolink-concat directive

src/repoma/.github/workflows/requirements-cron.yml
bb3a47f introduced a bug: it lets the requirements upgrade cron job on every other week, _but starting on the first day of each month_. The result is that the weekday on which the cron job runs switches each month. For certain months, this can also result in redundant pull requests like https://github.com/ComPWA/qrules/pull/148, https://github.com/ComPWA/ampform/pull/223, and https://github.com/ComPWA/tensorwaves/pull/408. (They have been modified to include the fix by this repo-maintenance PR.)
- See an example of a skipped job for an odd week here:
https://github.com/ComPWA/ampform/actions/runs/1778324274
- Similarly, here's a test run (cancelled) in case the week number is marked as even:
https://github.com/ComPWA/ampform/actions/runs/1778340043
=> fix: run requirements cron job on even weeks only

.pre-commit-hooks.yaml, README.md, setup.cfg, src/repoma/set_nb_cells.py
_Tested this PR https://github.com/ComPWA/ampform/pull/226._
Sub-hook `--fix-first-nbcell` has been renamed to `--set-nb-cell`. Use the following example config instead:
```yaml
- repo: https://github.com/ComPWA/repo-maintenance
rev: ...
hooks:
- id: set-nb-cells
args:
- --add-install-cell
- --additional-packages=IPython
- --extras-require=doc,viz
```
Notebooks can be ignored by adding a Markdown cell with comment ``.
- Added an import statement `from IPython.display import display`. This is to:
- help syntax highlighting when viewing the notebook in VS Code.
- render `display` statements as links in the documentation (see https://github.com/ComPWA/compwa-org/issues/106). See example of a [`display()`](https://ipython.readthedocs.io/en/8.0.1/api/generated/IPython.display.html#IPython.displ …
=> refactor: rename fix-first-nbcell to set-nb-cells

src/compwa_policy/check_dev_files/readthedocs.py, tests/check_dev_files/readthedocs/extend/.readthedocs-good.yml, tests/check_dev_files/readthedocs/overwrite/.readthedocs-good.yml
Since `uv` [v0.2.0](https://github.com/astral-sh/uv/releases/tag/0.2.0), `uv` is stricter with `python` discovery. It is now cleaner to run `python -m uv` where `python` comes from the virtual environment you are using.
For this, it is required to install `uv` into the environment instead of having it installed system-wide. This can simply be done with `python -m pip install 'uv>=0.2.0`.
_The new `.readthedocs.yml` has been tested on https://github.com/ComPWA/compwa.github.io/pull/279._
=> FIX: install `uv` through `pip`

.pre-commit-hooks.yaml, pyproject.toml, src/compwa_policy/remove_empty_tags.py, src/compwa_policy/set_nb_cells.py
Closes #349 
---
Added the following hook:
```yaml
repos:
- repo: https://github.com/ComPWA/policy
rev: ""
hooks:
- id: remove-empty-tags
```
This removes the `tags` cell metadata field from Jupyter notebooks if it is empty, e.g.:
```yaml
"metadata": {
"tags": []
}
```
```yaml
"metadata": {}
```
---
Also removing `slideshow` from the configure cell from `set-nb-cells` in order to address https://github.com/ComPWA/qrules/pull/277.
=> FEAT: remove tags from notebook cell if empty

src/compwa_policy/check_dev_files/ruff.py
It should still be possible to install `black` in the `doc` or `test` dependencies, even if `black` is removed from the `jupyter` dependencies since #324.
=> FIX: keep `black` in `doc` dependencies

src/compwa_policy/check_dev_files/ruff.py
Allow writing e.g. `dict(a=1, b=2)` in Jupyter notebooks. Key-word dictionaries are often used with `matplotlib` or `plotly`.
=> DX: allow `dict` with keyword arguments in notebooks

src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/precommit.py
Automatically adds the [`remove-empty-tags`](https://compwa.github.io/policy/api/compwa_policy.remove_empty_tags.html) hook if the repository has Jupyter notebooks.
=> ENH: automatically add `remove-empty-tag` hook

src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/nbstripout.py
The `check-dev-files` hook now has a `--allowed-cell-metadata` flag that takes a comma-separated list of cell metadata that should not be removed by `nbstripout`, for example `--allowed-cell-metadata=editable,slideshow`.
=> FEAT: implement `--allowed-cell-metadata` flag

.cspell.json, .envrc, src/compwa_policy/.template/.cspell.json, src/compwa_policy/check_dev_files/direnv.py
Follow-up to #354, now with support for `venv`, `uv venv`, and `pixi` environments.
=> ENH: support `pixi` and `venv` in `.envrc`

pyproject.toml, tox.ini
- Run `mypy` through Tox `sty` job
- Remove redundant `docnb` and `docnblive` job
- Install `pydeps` in developer environment so that it can be run without `tox` as well
- Wrap arguments that contain `*` in single quotation marks
=> MAINT: clean up Tox configuration

src/compwa_policy/check_dev_files/precommit.py
The ComPWA/policy hooks will now be moved right after `meta` .
=> BEHAVIOR: sort ComPWA/policy hooks right after `meta`

src/compwa_policy/utilities/toml.py, tests/utilities/test_toml.py
The `multiline` now defaults to `None`, which is the old behavior: the array is multiline if there is more than one item in the array. Setting `multiline=False` will force the array to be single line.
=> ENH: allow enforce single-line arrays

src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/conda.py, src/compwa_policy/check_dev_files/precommit.py
- Added a `--package-managers` flag that allows selecting which package managers to use for the developer environment. For now it only removes the `environment.yml` if `conda` is not listed in the `--package-managers`.
- The [`environment.yml`](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) configuration file for Conda is now automatically created if not available.
=> FEAT: create or remove Conda `environment.yml`

docs/conf.py, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/conda.py, src/compwa_policy/check_dev_files/pixi.py, src/compwa_policy/utilities/__init__.py, tests/check_dev_files/test_pixi.py
=> FEAT: remove Pixi configuration if not listed in `--package-managers`

src/compwa_policy/check_dev_files/nbstripout.py
=> ENH: add --drop-empty-cells tag in pre-commmit hook

src/compwa_policy/check_dev_files/black.py, src/compwa_policy/check_dev_files/citation.py, src/compwa_policy/check_dev_files/cspell.py, src/compwa_policy/check_dev_files/mypy.py, src/compwa_policy/check_dev_files/pixi.py, src/compwa_policy/check_dev_files/precommit.py, src/compwa_policy/check_dev_files/pyright.py, src/compwa_policy/check_dev_files/pytest.py, src/compwa_policy/check_dev_files/ruff.py, src/compwa_policy/check_dev_files/toml.py, src/compwa_policy/utilities/precommit/__init__.py, src/compwa_policy/utilities/precommit/setters.py, src/compwa_policy/utilities/pyproject/__init__.py, tests/utilities/precommit/test_class.py
This removes the `append_to_changelog()` method. Write `.changelog.append()` instead.
=> BREAK: expose `changelog` as property

.pre-commit-config.yaml, environment.yml, src/compwa_policy/.template/.cspell.json, src/compwa_policy/check_dev_files/precommit.py, src/compwa_policy/check_dev_files/prettier.py
See https://github.com/ComPWA/prettier-pre-commit
=> ENH: update Prettier pre-commit URL to ComPWA

.pre-commit-config.yaml, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/gitpod.py
The GitPod configuration can be added back by setting `--gitpod` with the `check-dev-files` hook.
=> BREAK: remove GitPod configuration by default

pyproject.toml, src/compwa_policy/check_dev_files/toml.py
Disable [`--sort-table-keys`](https://pypi.org/project/toml-sort) in [`toml-sort`](https://pypi.org/project/toml-sort). It is conflicting with Taplo v0.9.
=> FIX: do not sort table keys with `toml-sort`

src/compwa_policy/check_dev_files/pixi.py
Previously, the `env` table was created like this:
```toml
[tool.pixi.activation]  # <-- should be a super table
[tool.pixi.activation.env]
```
=> ENH: do not create `pixi.activation` table for `env`

src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/ruff.py
This is a temporary fix for https://github.com/ComPWA/compwa.github.io/pull/270 and related issues/PRs. It uses `isort` to move all imports to the top of a notebook and then Ruff will do the rest of the sorting.
In practice, by adding the `--imports-on-top` flag to the `check-dev-files hook, the following pre-commit hook will be added:
```yaml
- repo: https://github.com/nbQA-dev/nbQA
rev: 1.9.0
hooks:
- id: nbqa-isort
args: [--float-to-top]
```
---
_Update:_ You'll have to add the following to your `pyproject.toml` in order to be compatible with Ruff:
```toml
[tool.isort]
profile = "black"
```
=> FEAT: move `import`s to top in notebooks

.vscode/settings.json, src/compwa_policy/check_dev_files/vscode.py
The `python.analysis.typeCheckingMode` setting in VS Code is not needed if there is a `pyright` conviguration in `pyproject.toml`.
=> DX: remove `python.analysis.typeCheckingMode` setting

pyproject.toml, src/compwa_policy/check_dev_files/pixi.py, src/compwa_policy/check_dev_files/precommit.py, src/compwa_policy/utilities/python.py
=> ENH: switch to `pre-commit-uv`

src/compwa_policy/utilities/cfg.py
The `extract_config_section()` function is not used anywhere in the codebase.
=> BREAK: remove redundant `extract_config_section()` function

pyproject.toml, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/cspell.py, src/compwa_policy/check_dev_files/github_workflows.py, src/compwa_policy/check_dev_files/pyproject.py, src/compwa_policy/utilities/precommit/setters.py, src/compwa_policy/utilities/pyproject/getters.py
This PR fixes a few bugs if `--no-pypi` is specified:
- The `pypi` publish step is removed from the `cd.yml` workflow.
- [`classsifiers`](https://pypi.org/classifiers) are removed from `pyproject.toml`, because they are only used by PyPI.
- Some autofixes for `.pre-commit-config.yaml` are now fixed.
=> ENH: clean up classifiers and workflows if `--no-pypi`

src/compwa_policy/check_dev_files/readthedocs.py
The `.readthedocs.yml` configuration file is now updated if `--package-manager` is set to `uv`, `pixi` or `pixi+uv`.
- Closes https://github.com/ComPWA/policy/issues/76
=> ENH: update RTD config for `uv` or `pixi` manager

.cspell.json, .pre-commit-config.yaml, .vscode/settings.json, src/compwa_policy/.template/.cspell.json, src/compwa_policy/.template/.prettierrc, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/prettier.py, src/compwa_policy/utilities/__init__.py
Removed the check that updates or removes the [`.prettierrc`](https://prettier.io/docs/en/configuration.html) file.
=> BREAK: remove `--no-prettierrc` flag

src/compwa_policy/check_dev_files/black.py, src/compwa_policy/check_dev_files/pyupgrade.py, src/compwa_policy/check_dev_files/ruff.py, src/compwa_policy/check_dev_files/toml.py, src/compwa_policy/utilities/yaml.py
=> MAINT: extract function for `YAML(typ="rt").load`

src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/github_workflows.py
The `cd.yml` workflow is removed if there are no jobs.
=> FEAT: add `--no-milestone` flag to `check-dev-files`

.github/workflows/lock.yml, .pre-commit-config.yaml, src/compwa_policy/.github/workflows/lock.yml, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/update_lock.py
The default argument for `--update-lock-files` has been set to `outsource`, which means that it waits for [pre-commit.ci](https://pre-commit.ci) to create a PR.
=> BEHAVIOR: update lock files by default

src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/binder.py, src/compwa_policy/utilities/__init__.py
- Closes https://github.com/ComPWA/policy/issues/64
=> FEAT: automatically update Binder configuration

.cspell.json, .gitignore, .prettierrc.yml, .vscode/settings.json, CONTRIBUTING.md, pyproject.toml, src/compwa_policy/.template/.cspell.json, src/compwa_policy/.template/CONTRIBUTING.md.jinja, src/compwa_policy/check_dev_files/pixi/_update.py, src/compwa_policy/check_dev_files/precommit.py, src/compwa_policy/check_dev_files/tox.py, src/compwa_policy/utilities/pyproject/setters.py, src/compwa_policy/utilities/python.py
Closes https://github.com/ComPWA/policy/issues/450
=> ENH: remove `pre-commit-uv` and `tox-uv` from environment

src/compwa_policy/check_dev_files/jupyter.py
=> FIX: do not remove `jupyterlab-code-formatter`

.cspell.json, .github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, src/compwa_policy/.github/workflows/ci.yml, src/compwa_policy/check_dev_files/binder.py, src/compwa_policy/check_dev_files/jupyter.py, src/compwa_policy/check_dev_files/pyproject.py, src/compwa_policy/check_dev_files/readthedocs.py, src/compwa_policy/check_dev_files/ruff.py, src/compwa_policy/check_dev_files/update_lock.py, src/compwa_policy/utilities/pyproject/__init__.py, src/compwa_policy/utilities/pyproject/_struct.py, src/compwa_policy/utilities/pyproject/setters.py, tests/utilities/pyproject/test_setters.py
=> FEAT: convert dev dependencies to dependency groups

CONTRIBUTING.md, src/compwa_policy/.template/CONTRIBUTING.md.jinja, src/compwa_policy/check_dev_files/binder.py, src/compwa_policy/check_dev_files/readthedocs.py
`uv run` and `uv sync` install all dependency groups by default. To limit the dependencies per job, this adds the [`--no-dev` flag](https://docs.astral.sh/uv/reference/cli/#uv-run).
_See also https://github.com/ComPWA/actions/pull/115_
=> FIX: add `--no-dev` flag if using `--group` flag

src/compwa_policy/check_dev_files/precommit.py
Previously, if `.pre-commit-config.yaml` did not have a `ci.skip` section, skipped hooks would not be added.
=> FIX: create `ci` section if missing

.pre-commit-config.yaml, src/compwa_policy/check_dev_files/citation.py, src/compwa_policy/check_dev_files/precommit.py, src/compwa_policy/check_dev_files/readthedocs.py, src/compwa_policy/check_dev_files/ruff.py, src/compwa_policy/utilities/executor.py, src/compwa_policy/utilities/precommit/__init__.py, src/compwa_policy/utilities/precommit/setters.py, src/compwa_policy/utilities/precommit/struct.py, src/compwa_policy/utilities/pyproject/__init__.py, src/compwa_policy/utilities/pyproject/_struct.py, src/compwa_policy/utilities/pyproject/setters.py
Also implements the new linting and formatting rules of [Ruff v0.8](https://astral.sh/blog/ruff-v0.8.0#new-error-codes-for-flake8-type-checking-rules).
=> MAINT: update lock files

.cspell.json, src/compwa_policy/.template/.cspell.json, src/compwa_policy/check_dev_files/cspell.py
`useGitignore` is now set to `true` in the `.cspell.json` configuration file.
=> ENH: respect `.gitignore` with cSpell

.github/workflows/ci.yml, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/github_workflows.py
Imports the environment variables specified by the `--environment-variables` argument of the `check-dev-files` hook into the `ci.yml` workflow.
=> ENH: import environment variables into `ci.yml`

.github/workflows/sync-labels.yml, labels/default.toml, labels/physics.toml
=> DX: update Epic label to include emoji

src/compwa_policy/check_dev_files/readthedocs.py
Fixes this problem:
https://readthedocs.org/projects/compwa/builds/26805707/
=> FIX: remove `uv --locked` flag from RTD config

pyproject.toml, src/compwa_policy/check_dev_files/readthedocs.py, tests/check_dev_files/readthedocs/extend/.readthedocs-bad.yml, tests/check_dev_files/readthedocs/extend/.readthedocs-good.yml, tests/check_dev_files/readthedocs/overwrite/.readthedocs-bad1.yml, tests/check_dev_files/readthedocs/overwrite/.readthedocs-bad2.yml, tests/check_dev_files/readthedocs/overwrite/.readthedocs-good.yml
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config
=> ENH: set `sphinx.configuration`

pyproject.toml, src/compwa_policy/utilities/pyproject/_struct.py, src/compwa_policy/utilities/pyproject/setters.py
- Closes https://github.com/ComPWA/actions/issues/124
https://github.com/ComPWA/actions/issues/124 fixed a bug where the tests were not run on older Python versions. That resulted in a bug, see
https://github.com/ComPWA/policy/actions/runs/12829577195/job/35775927364
This PR fixes that problem.
=> FIX: avoid Python 3.10 syntax

codecov.yml, pyproject.toml, src/compwa_policy/check_dev_files/pytest.py, src/compwa_policy/utilities/pyproject/__init__.py
=> ENH: exclude `TYPE_CHECKING` from test coverage

pyproject.toml
See #496 
The `tox` command will now essentially run all CI checks locally. You can also run all unit tests on all Python versions using the `test` label as follows
```shell
tox -m test
```
=> DX: run tests with all python versions through Tox

.cspell.json, .pre-commit-hooks.yaml, pyproject.toml, src/compwa_policy/check_dev_files/precommit.py, src/compwa_policy/set_nb_display_name.py
The Jupyter notebook kernel name in Jupyter Lab is always set to `"Python 3 (ipykernel)"`, while VS Code sets the name to `".venv"` if the `uv` environment is selected. This is annoying in PR diffs.
This PR adds a new hook, `set-nb-display-name`, that always sets the kernel name to the name used by Jupyter Lab. The `check-dev-files` hook installs this hook automatically if the repository contains `*.ipynb` files.
=> ENH: always overwrite kernel name to "Python 3 (ipykernel)"

src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/tox.py
Follow-up to #498, which automatically updates the Tox labels and `env_list` if it contains any strings like `"3.10"`.
=> ENH: update Tox labels and env_list

src/compwa_policy/check_dev_files/readthedocs.py
Required fix for https://github.com/ComPWA/policy/issues/496
=> FIX: install `tox-uv` on RTD

.github/workflows/ci.yml, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/github_workflows.py
- BEHAVIOR: run MacOS tests on Python 3.10 by default
=> BREAK: rename `--no-macos` to `--macos-python-version`

src/compwa_policy/set_nb_display_name.py
Follow-up to #499 for projects that use [`pyproject-local-kernel`](https://bluss.github.io/pyproject-local-kernel).
=> FIX: set kernel name to "Pyproject Local"

.pre-commit-config.yaml, src/compwa_policy/check_dev_files/__init__.py, src/compwa_policy/check_dev_files/precommit.py, tests/utilities/precommit/test_getters.py
- Sets the [`autofix_commit_msg`](https://pre-commit.ci/#configuration) for pre-commit.ci.
- Changed the PR title to "MAINT: ~update~upgrade lock files" in consistency with `uv lock --upgrade`
=> ENH: set commit message for pre-commit.ci autofixes

.vscode/settings.json, src/compwa_policy/check_dev_files/mypy.py
Mypy crashes in VS Code in repositories with a large number of dependencies if [`mypy-type-checker.importStrategy`](https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker) is set to `fromEnvironment`.
=> FIX: remove `mypy-type-checker.importStrategy`
